name: ğŸ—‘ï¸ åˆ é™¤æ—§çš„å·¥ä½œæµ

on:
  workflow_dispatch:   # æ‰‹åŠ¨è§¦å‘
  workflow_run:       # åœ¨ Build workflow å®Œæˆåè§¦å‘
    workflows: ["ğŸš€ ç£Šç§‘ N60 Pro 512é—ªå­˜"]   # å¡«ä½  Build workflow çš„åå­—
    types:
      - completed
  schedule:
    - cron: 0 3 * * *

jobs:
  Cleaning:
    runs-on: self-hosted

    steps:
    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 0
        keep_minimum_runs: 0

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 15
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
